# NumPy Tutorial for Machine Learning

This tutorial introduces NumPy, the fundamental library for numerical computing in Python. NumPy is essential for Machine Learning because it provides fast array operations that are the building blocks for neural networks.

---

## Why NumPy?

| Python Lists | NumPy Arrays |
|--------------|-------------|
| Slow (loops) | Fast (vectorized) |
| General purpose | Optimized for numbers |
| No math operations | Built-in math operations |

**Example:** Adding two lists of 1 million numbers:
- Python lists: ~100ms
- NumPy arrays: ~1ms (100x faster!)

The speed of NumPy stems from its use of contiguous memory layout with fixed data types, enabling vectorized operations executed in **pre-compiled C code** that bypass Python's interpreter overhead and per-element type checking.

---

In [1]:
import numpy as np

# This is the standard way to import NumPy
print(f"NumPy version: {np.__version__}")

NumPy version: 2.0.1


---

# Part 1: Creating Arrays

NumPy arrays are like Python lists, but more powerful.

## 1.1 From Python Lists

The simplest way to create a NumPy array is from a Python list.

In [2]:
# Creating a 1D array (vector)
python_list = [1, 2, 3, 4, 5]
numpy_array = np.array(python_list)

print(f"Python list: {python_list}")
print(f"NumPy array: {numpy_array}")
print(f"Type: {type(numpy_array)}")

Python list: [1, 2, 3, 4, 5]
NumPy array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>


In [3]:
# Creating a 2D array (matrix)
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Matrix:")
print(matrix)

Matrix:
[[1 2 3]
 [4 5 6]]


### ✏️ Task 1.1

Create a NumPy array containing the values `[10, 20, 30, 40, 50]`.

In [5]:
# Your code here
my_array = ...

print(my_array)

Ellipsis


## 1.2 Special Arrays

NumPy provides functions to create commonly needed arrays.

In [6]:
# Array of zeros
zeros = np.zeros(5)
print(f"Zeros: {zeros}")

# Array of ones
ones = np.ones(4)
print(f"Ones: {ones}")

# Array with a range of numbers
range_array = np.arange(0, 10, 2)  # start, stop, step
print(f"Range (0 to 10, step 2): {range_array}")

# Array with evenly spaced numbers
linspace = np.linspace(0, 1, 5)  # start, stop, num_points
print(f"Linspace (0 to 1, 5 points): {linspace}")

Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1.]
Range (0 to 10, step 2): [0 2 4 6 8]
Linspace (0 to 1, 5 points): [0.   0.25 0.5  0.75 1.  ]


In [7]:
# 2D arrays of zeros and ones
zeros_2d = np.zeros((2, 3))  # 2 rows, 3 columns
print("2D Zeros (2x3):")
print(zeros_2d)

ones_2d = np.ones((3, 2))  # 3 rows, 2 columns
print("\n2D Ones (3x2):")
print(ones_2d)

2D Zeros (2x3):
[[0. 0. 0.]
 [0. 0. 0.]]

2D Ones (3x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]]


### ✏️ Task 1.2

Create:
1. A 1D array of 10 zeros
2. A 3x3 matrix filled with ones
3. An array with numbers from 0 to 100 in steps of 10

In [ ]:
# Your code here
zeros_10 = ...
ones_3x3 = ...
range_0_100 = ...

print(f"1) {zeros_10}")
print(f"2)\n{ones_3x3}")
print(f"3) {range_0_100}")

## 1.3 Random Arrays

Random arrays are essential for initializing neural network weights.

In [ ]:
# Set seed for reproducibility
np.random.seed(42)

# Random values between 0 and 1
random_uniform = np.random.rand(5)
print(f"Random uniform [0,1]: {random_uniform}")

# Random integers
random_int = np.random.randint(1, 10, size=5)  # min, max, size
print(f"Random integers [1,10): {random_int}")

# Random values from normal distribution (mean=0, std=1)
random_normal = np.random.randn(5)
print(f"Random normal: {random_normal}")

In [ ]:
# 2D random array (like weight matrices in neural networks)
weights = np.random.randn(3, 4)  # 3 rows, 4 columns
print("Random weight matrix (3x4):")
print(weights)

### ✏️ Task 1.3

Create a random weight matrix of shape 4x3 (4 rows, 3 columns) using the normal distribution.

In [ ]:
# Your code here
weight_matrix = ...

print(weight_matrix)
print(f"Shape: {weight_matrix.shape}")

---

# Part 2: Array Properties

Understanding the shape and dimensions of arrays is crucial for ML.

In [8]:
# Create sample arrays
vector = np.array([1, 2, 3, 4, 5])
matrix = np.array([[1, 2, 3], [4, 5, 6]])
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("Vector:", vector)
print(f"  shape: {vector.shape}")
print(f"  ndim: {vector.ndim}")
print(f"  size: {vector.size}")

print("\nMatrix:")
print(matrix)
print(f"  shape: {matrix.shape}")
print(f"  ndim: {matrix.ndim}")
print(f"  size: {matrix.size}")

print("\nTensor (3D):")
print(tensor)
print(f"  shape: {tensor.shape}")
print(f"  ndim: {tensor.ndim}")

Vector: [1 2 3 4 5]
  shape: (5,)
  ndim: 1
  size: 5

Matrix:
[[1 2 3]
 [4 5 6]]
  shape: (2, 3)
  ndim: 2
  size: 6

Tensor (3D):
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
  shape: (2, 2, 2)
  ndim: 3


### Key Properties:

| Property | Description | Example (2x3 matrix) |
|----------|-------------|---------------------|
| `.shape` | Dimensions as tuple | `(2, 3)` |
| `.ndim` | Number of dimensions | `2` |
| `.size` | Total number of elements | `6` |
| `.dtype` | Data type | `float64` |

### ✏️ Task 2.1

Create a 4x5 matrix of random numbers and print its shape, number of dimensions, and total size.

In [ ]:
# Your code here
my_matrix = ...

print(f"Shape: ...")
print(f"Dimensions: ...")
print(f"Total elements: ...")

---

# Part 3: Indexing and Slicing

Accessing elements in arrays works similar to Python lists, but with more power.

## 3.1 Basic Indexing

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print(f"Array: {arr}")
print(f"First element (index 0): {arr[0]}")
print(f"Last element (index -1): {arr[-1]}")
print(f"Third element (index 2): {arr[2]}")

In [ ]:
# 2D array indexing: [row, column]
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Matrix:")
print(matrix)
print(f"\nElement at row 0, col 0: {matrix[0, 0]}")
print(f"Element at row 1, col 2: {matrix[1, 2]}")
print(f"Element at row 2, col 1: {matrix[2, 1]}")

## 3.2 Slicing

In [ ]:
arr = np.array([0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

print(f"Array: {arr}")
print(f"First 3 elements [0:3]: {arr[0:3]}")
print(f"Elements 3 to 6 [3:7]: {arr[3:7]}")
print(f"Last 3 elements [-3:]: {arr[-3:]}")
print(f"Every 2nd element [::2]: {arr[::2]}")

In [ ]:
# 2D slicing
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Matrix:")
print(matrix)
print(f"\nFirst row: {matrix[0, :]}")
print(f"First column: {matrix[:, 0]}")
print(f"Top-left 2x2:\n{matrix[0:2, 0:2]}")
print(f"Last two columns:\n{matrix[:, -2:]}")

### ✏️ Task 3.1

Given the matrix below, extract:
1. The second row
2. The third column
3. The bottom-right 2x2 submatrix

In [ ]:
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

# Your code here
second_row = ...
third_column = ...
bottom_right = ...

print(f"Second row: {second_row}")
print(f"Third column: {third_column}")
print(f"Bottom-right 2x2:\n{bottom_right}")

---

# Part 4: Array Operations

This is where NumPy really shines! Operations are applied element-wise automatically.

## 4.1 Element-wise Operations

In [9]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print(f"a = {a}")
print(f"b = {b}")
print(f"\na + b = {a + b}")
print(f"a - b = {a - b}")
print(f"a * b = {a * b}")
print(f"a / b = {a / b}")
print(f"a ** 2 = {a ** 2}")

a = [1 2 3 4]
b = [10 20 30 40]

a + b = [11 22 33 44]
a - b = [ -9 -18 -27 -36]
a * b = [ 10  40  90 160]
a / b = [0.1 0.1 0.1 0.1]
a ** 2 = [ 1  4  9 16]


In [ ]:
# Scalar operations (applied to all elements)
arr = np.array([1, 2, 3, 4])

print(f"arr = {arr}")
print(f"arr + 10 = {arr + 10}")
print(f"arr * 2 = {arr * 2}")
print(f"arr / 2 = {arr / 2}")

## 4.2 Mathematical Functions

In [ ]:
arr = np.array([1, 4, 9, 16, 25])

print(f"arr = {arr}")
print(f"sqrt(arr) = {np.sqrt(arr)}")
print(f"exp(arr) = {np.exp(arr)}")
print(f"log(arr) = {np.log(arr)}")

In [ ]:
# Functions commonly used in neural networks
x = np.array([-2, -1, 0, 1, 2])

print(f"x = {x}")
print(f"\nexp(x) = {np.exp(x)}")
print(f"maximum(0, x) = {np.maximum(0, x)}")

### ✏️ Task 4.1

Given an array `x`, compute:
1. Each element squared
2. The square root of each element
3. `e^x` for each element

In [ ]:
x = np.array([1, 2, 3, 4, 5])

# Your code here
squared = ...
sqrt = ...
exp = ...

print(f"x = {x}")
print(f"x² = {squared}")
print(f"√x = {sqrt}")
print(f"eˣ = {exp}")

---

# Part 5: Aggregation Functions

Functions that reduce an array to a single value (or smaller array).

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(f"arr = {arr}")
print(f"\nSum: {np.sum(arr)}")
print(f"Mean: {np.mean(arr)}")
print(f"Std: {np.std(arr):.2f}")
print(f"Min: {np.min(arr)}")
print(f"Max: {np.max(arr)}")
print(f"Argmax (index of max): {np.argmax(arr)}")

## 5.1 Aggregation Along Axes

For 2D arrays, you can aggregate along rows or columns.

In [ ]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Matrix:")
print(matrix)
print(f"\nSum of all elements: {np.sum(matrix)}")
print(f"Sum along axis=0 (columns): {np.sum(matrix, axis=0)}")
print(f"Sum along axis=1 (rows): {np.sum(matrix, axis=1)}")

### Visual Guide to Axes:

```
        axis=1 →
       [1, 2, 3]    → sum = 6
axis=0 [4, 5, 6]    → sum = 15
  ↓     ↓  ↓  ↓
        5  7  9
```

### ✏️ Task 5.1

Given the matrix below:
1. Find the maximum value in the entire matrix
2. Find the maximum value in each row
3. Find the mean of each column

In [ ]:
matrix = np.array([
    [3, 7, 2],
    [8, 1, 5],
    [4, 9, 6]
])

# Your code here
overall_max = ...
row_max = ...
col_mean = ...

print(f"Matrix:\n{matrix}")
print(f"\nOverall max: {overall_max}")
print(f"Max per row: {row_max}")
print(f"Mean per column: {col_mean}")

---

# Part 6: Matrix Operations (Essential for Neural Networks!)

Matrix multiplication is THE core operation in neural networks.

## 6.1 Dot Product

In [ ]:
# Dot product of two vectors
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# a · b = 1*4 + 2*5 + 3*6 = 4 + 10 + 18 = 32
dot_product = np.dot(a, b)

print(f"a = {a}")
print(f"b = {b}")
print(f"a · b = {dot_product}")

## 6.2 Matrix Multiplication

**Rule:** For `A @ B`, the number of columns in A must equal the number of rows in B.

If A is `(m, n)` and B is `(n, p)`, then A @ B is `(m, p)`.

In [ ]:
# Matrix-vector multiplication (used in neural networks!)
W = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])  # Shape: (3, 2)

x = np.array([1, 2])  # Shape: (2,)

# W @ x: (3, 2) @ (2,) = (3,)
result = np.dot(W, x)

print(f"W (3x2):\n{W}")
print(f"\nx (2,): {x}")
print(f"\nW @ x = {result}")
print(f"Result shape: {result.shape}")

In [ ]:
# Matrix-matrix multiplication
A = np.array([[1, 2], [3, 4]])  # (2, 2)
B = np.array([[5, 6], [7, 8]])  # (2, 2)

# You can use np.dot() or the @ operator
C = A @ B  # Same as np.dot(A, B)

print(f"A:\n{A}")
print(f"\nB:\n{B}")
print(f"\nA @ B:\n{C}")

---

# Part 7: Reshaping Arrays

Often you need to change the shape of arrays without changing the data.

In [ ]:
# Reshape a 1D array to 2D
arr = np.arange(12)  # [0, 1, 2, ..., 11]
print(f"Original: {arr}")
print(f"Shape: {arr.shape}")

# Reshape to 3x4
reshaped = arr.reshape(3, 4)
print(f"\nReshaped (3x4):\n{reshaped}")

# Reshape to 4x3
reshaped2 = arr.reshape(4, 3)
print(f"\nReshaped (4x3):\n{reshaped2}")

In [ ]:
# Using -1 to auto-calculate one dimension
arr = np.arange(12)

# "Give me 3 rows, calculate columns automatically"
reshaped = arr.reshape(3, -1)
print(f"reshape(3, -1):\n{reshaped}")

# "Give me 4 columns, calculate rows automatically"
reshaped2 = arr.reshape(-1, 4)
print(f"\nreshape(-1, 4):\n{reshaped2}")

In [ ]:
# Flatten: Convert any array to 1D
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Matrix:\n{matrix}")
print(f"\nFlattened: {matrix.flatten()}")

# This is how images are fed into neural networks!
# A 28x28 image becomes a 784-element vector

### ✏️ Task 7.1

1. Create a 1D array with values 1 to 24
2. Reshape it to a 4x6 matrix
3. Reshape it to a 2x3x4 tensor (3D array)
4. Flatten the tensor back to 1D

In [ ]:
# Your code here
arr = ...
matrix_4x6 = ...
tensor_2x3x4 = ...
flattened = ...

print(f"Original shape: {arr.shape}")
print(f"4x6 matrix shape: {matrix_4x6.shape}")
print(f"2x3x4 tensor shape: {tensor_2x3x4.shape}")
print(f"Flattened shape: {flattened.shape}")

---

# Part 8: Broadcasting

Broadcasting allows operations between arrays of different shapes.

In [ ]:
# Adding a scalar to an array (simplest broadcasting)
arr = np.array([1, 2, 3])
print(f"arr + 10 = {arr + 10}")

In [ ]:
# Adding a vector to each row of a matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
bias = np.array([10, 20, 30])

print(f"Matrix:\n{matrix}")
print(f"\nBias: {bias}")
print(f"\nMatrix + Bias:\n{matrix + bias}")

---

# Part 9: Boolean Indexing

Select elements based on conditions.

In [ ]:
arr = np.array([1, -2, 3, -4, 5, -6])

print(f"Array: {arr}")
print(f"\nPositive mask: {arr > 0}")
print(f"Positive elements: {arr[arr > 0]}")
print(f"Negative elements: {arr[arr < 0]}")

In [ ]:
# np.where: conditional selection
arr = np.array([-2, -1, 0, 1, 2])

# ReLU using np.where!
relu_result = np.where(arr > 0, arr, 0)
print(f"Array: {arr}")
print(f"ReLU: {relu_result}")

# Or simply use np.maximum
print(f"ReLU (using maximum): {np.maximum(0, arr)}")

### ✏️ Task 9.1

Given an array of test scores, find:
1. All passing scores (>= 60)
2. The number of failing scores (< 60)
3. Replace all failing scores with 0

In [ ]:
scores = np.array([85, 45, 72, 58, 90, 62, 38, 95])

# Your code here
passing = ...
num_failing = ...
scores_adjusted = ...  # Hint: use np.where

print(f"Original scores: {scores}")
print(f"Passing scores: {passing}")
print(f"Number of failing: {num_failing}")
print(f"Adjusted scores: {scores_adjusted}")

---

# Summary: NumPy Operations for ML

| Operation | NumPy Function | ML Use Case |
|-----------|---------------|-------------|
| Create array | `np.array()`, `np.zeros()`, `np.ones()` | Initialize data |
| Random array | `np.random.randn()` | Initialize weights |
| Matrix multiply | `np.dot()` or `@` | Layer computation |
| Element-wise | `+`, `-`, `*`, `/` | Bias addition, scaling |
| Maximum | `np.maximum(0, x)` | ReLU activation |
| Exponential | `np.exp()` | Softmax activation |
| Sum | `np.sum()` | Softmax normalization |
| Argmax | `np.argmax()` | Get predicted class |
| Reshape | `.reshape()` | Flatten images |

---

---

# Solutions

**Only look after trying the tasks yourself!**

In [10]:
show_solutions = False  # Change to True to see solutions

if show_solutions:
    print("""
SOLUTIONS
=========

Task 1.1: my_array = np.array([10, 20, 30, 40, 50])

Task 1.2:
  zeros_10 = np.zeros(10)
  ones_3x3 = np.ones((3, 3))
  range_0_100 = np.arange(0, 101, 10)

Task 1.3: weight_matrix = np.random.randn(4, 3)

Task 2.1:
  my_matrix = np.random.rand(4, 5)
  print(f"Shape: {my_matrix.shape}")
  print(f"Dimensions: {my_matrix.ndim}")
  print(f"Total elements: {my_matrix.size}")

Task 3.1:
  second_row = matrix[1, :]
  third_column = matrix[:, 2]
  bottom_right = matrix[-2:, -2:]

Task 4.1:
  squared = x ** 2
  sqrt = np.sqrt(x)
  exp = np.exp(x)

Task 5.1:
  overall_max = np.max(matrix)
  row_max = np.max(matrix, axis=1)
  col_mean = np.mean(matrix, axis=0)

Task 7.1:
  arr = np.arange(1, 25)
  matrix_4x6 = arr.reshape(4, 6)
  tensor_2x3x4 = arr.reshape(2, 3, 4)
  flattened = tensor_2x3x4.flatten()

Task 9.1:
  passing = scores[scores >= 60]
  num_failing = np.sum(scores < 60)
  scores_adjusted = np.where(scores >= 60, scores, 0)
    """)